version: '3.8'

services:
  drupal:
    image: drupal:10
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:
